### ISSUE TITLE
Users in different voice channels (or no channel) able to give the bot commands.

### ISSUE THREAD

**Issue by pxdn1** [porridgewithraisins/jam-bot#1]
Hi, I have 3-4 of these running in a Discord and for the most part they seem to work pretty well!

I did notice something though that lends itself to people trolling and being malicious with the bot though which I think would classify as an issue.

Would it be possible to update the bot so that users that aren't in the same voice channel as the bot be ignored if they're trying to use a command such as !skip or !quit? Also, could you please figure out a way (via role id maybe) to allow certain users to control the bot sort-of like how Rythm did with the DJ role?

So far I love the bought though! Lightweight, easy to setup and seems to work well thus far.

Thanks!

**Comment by porridgewithraisins** [comment]
Hey, thanks for using the bot!

I have yet to add measures to curb trolling, and so on. I also completely forgot about the use case with multiple voice channels. I will make it so that the bot only accepts commands from people sharing the same voice channel as itself. I will couple this with releasing the permissions system like rythm's DJ role. If you have any suggestions, feel free to let me know. If you want to contribute, make a PR!

**Comment by porridgewithraisins** [comment]
Now, when multiple instances of the bot are running in the same guild, each instance only responds to commands sent by members it shares a voice channel with.


I will address the DJ role -- and related permissions settings in another commit, referencing your other issue.
